This is my hello world code for creating a 3d model step file:

```python
# Using Python 3.10.6 and ran: "pip install cadquery==2.4.0 numpy==1.23.5"

# Example using CadQuery to create a cylinder model

import cadquery as cq

# Create a cylinder with height 50mm and radius 10mm
cylinder_model = cq.Workplane("XY").cylinder(50, 10)

# Export the model to an STL file
output_file = "cylinder_model.stl"
cq.exporters.export(cylinder_model, output_file)

output_file
```

I want you to create a full version of this code that entirely produces the final 3d model I want based on my detailed description.

Start with a cylinder of diameter 28mm, and height 8.3mm.

Hollow-out the cylinder all the way through (the entire 8.3mm height) with a 17.60mm circle at the center.

Now we have a shape that looks like a toilet paper role (with rather thick surrounding).

This toilet paper role has walls with thickness: (28mm - 17.60mm) / 2 == 5.2mm

That gives us just enough space to make holes at the top of the cylinder for neodymium disc magnets of diameter 4mm.

We'll make the holes 4.04mm in diameter to leave some room for the superglew.
This means that in practice we're leaving 5.2mm - 4.04mm / 2 == 0.58mm of distance away from each side of the walls- internal and external.

Let's calculate the imaginary circle radius on which all magnet hole centers will be placed:
(17.60mm / 2) + 0.58mm + (4.04mm / 2) == 11.4mm radius

Which means, the center of each of the holes we're gonna drill into the top of the toilet paper role walls are all distance 11.4mm from the center.

That circle radius means we have room for 17 magnet holes 4.04mm in diameter, drawn perfectly equally spaced from each other (rather small spacing) along the 11.4mm radius.

However, I want you to draw only 16 magnet holes so that it's more symmetrical and divides 360 degrees more nicely.

The required depth of each of the magnet hole cylinder pockets: 3.3mm


In summary, the measurements have to be precise and specific, but altogether it's rather simple:
We start with a cylinder, drill a hole in the center, and drill 16 pockets around a circle at the top.
