I had this CNC machined in stainless steel 303. Specifically I had two of these manufactured to be used one on top of the other (face to face, magnets attaching to each other).

Now I need you to create an entirely new Python file that produces for me: `rangers_guard_sleeve_01_00_00.py`.

I will provide the entire readme of my full project for you to glance at to give you further context, **then** I will explain the requirements for the `rangers_guard_sleeve` after you read the readme, and see the provided example code.

magnet_holes_01_00_01.py
```py
"""
Creates a 'toilet paper roll' shaped cylinder with:
  - Outer diameter: 28.0 mm
  - Inner hole diameter: 17.6 mm (fully through)
  - Height: 8.3 mm
Then adds 16 equally spaced magnet holes at the top:
  - Diameter: 4.10 mm
  - Depth: 3.3 mm
  - Circle radius for hole centers: 11.4 mm
Exports the model to both STL and STEP formats.
"""

import cadquery as cq

# === 1. Create main cylinder ===
#   - Outer diameter: 28 mm ‚Üí radius = 14 mm
#   - Height: 8.3 mm
model = (
    cq.Workplane("XY")
    .circle(14)        # radius for 28 mm diameter
    .extrude(8.3)      # height
)

# === 2. Hollow out the center (like a toilet paper roll) ===
#   - Through-hole with diameter: 17.6 mm ‚Üí radius = 8.8 mm
model = (
    model
    .faces(">Z")               # pick the top face
    .workplane()               # create a new workplane on that face
    .hole(17.6)                # cut a 17.6 mm diameter hole all the way through
)

# === 3. Drill the magnet holes around the top face ===
#   - 16 holes
#   - Each hole diameter: 4.10 mm
#   - Hole depth: 3.3 mm
#   - Hole centers on a circle of radius: 11.4 mm
#     so they are equally spaced 360/16=22.5 degrees apart
model = (
    model
    .faces(">Z")               # pick the top face again
    .workplane()               # new workplane for drilling
    .polarArray(radius=11.4, startAngle=0, angle=360, count=16, fill=True)  # 16 holes in a full circle
    .hole(diameter=4.10, depth=3.3)  # create the holes as pockets in the top
)

# === 4. Export the final model to both STL and STEP files ===
output_file_step = "magnet_holes.step"
output_file_stl = "magnet_holes.stl"

# Export to STEP format
cq.exporters.export(model, output_file_step)

# Export to STL format
cq.exporters.export(model, output_file_stl)

# Print file names for confirmation
print(f"Model exported to: {output_file_step}")
print(f"Model exported to: {output_file_stl}")
```

```md
# Problem Statement

SanwuLasers‚Ñ¢Ô∏è Lasers such as Striker, Challenger II, Laser Rangers all have option for high powered blue diode (~7 watts).

SanwuLasers‚Ñ¢Ô∏è offers flashlight adapters that [can be screwed onto the top](./docs/laser_and_flashlight_adapter.jpg). It's generic, the flashlight adapter fits all of the aforementioned host types.

Problem is: It takes way too long to physically unscrew the flashlight adapter, and it's way too annoying to screw it back on. It should be possible to just pull it off, and snap it right back in place üß≤.

[magnet holes standard triangle language](./magnet_holes.stl)

![Fully assembled](./docs/xometry_final_result_cropped.png)

# Solution

Custom order for CNC machined stainless steel part that converts the screw-on mechanism into a magnetic mechanism!

The flashlight adapter can be ordered with an [Adapter for striker](#threads). This adapter is super useful because it's already threaded with male and female sides.

The generic custom machined part has 16 small holes, each 4.10mm in diameter and 3.30mm depth.

It just so happens that in practice, my choice of 3.30mm depth works with the [neodymium disc magnets](./docs/neodymium_magnets_amazon_listing.png) I chose, which according to the listing are **2mm in height** (apparently they're less). 

It just so happens that the specific magnets I bought, somehow [fit perfectly](./docs/two_stacked_magnets_fit_in_3.3mm_hole_perfectly.jpg) into the 3.3mm hole when two are stacked on each other in each hole and with super glue prepared at the bottom (no super glue between the two magnets).

The magnets are **very** slightly extruding which does cause purple light to be slightly visible when flashlight mode is on, but it's still a [tight fit](./docs/tight_fit_despite_magnets_slightly_extruding.jpg).

The small gap is also a feature- it causes the flashlight adapter to **not** be air-tight which makes it easier to change focus without causing a vacuum (which was a feature that was bothering me in the default flashlight adapter behaviour).

I originally chose 4.04mm hole width but that was not enough to leave room for machine tolerance and temperature changes, so then I changed the design to 4.10mm hole to make it easier to push-in the magnets.

# Process

I learned the recently released `FreeCAD 1.0.0`, but I gave up on the design once I understood that the software requires the user to draw shapes with my laptop's touchpad. I'm not an artist üé®üßë‚Äçüé®.

I decided it's much more robust to define the 3d design with words and precise measurements than it is to start drawing like a preschool child.

Therefore **for the initial version** I had `ChatGPT o1` write Python code to generate both a `.step` file and an `.stl` file, using [this prompt](./prompt.txt).

I use the `.stl` file to view the design in `Microsoft Paint 3d`, I then uploaded the `.step` file as-is to `Xometry` website.

I chose standard stainless steel [settings in the website](./docs/xometry_order_settings.png) with the lowest tolerance quality.

The reason I chose such a low tolerance quality is that I'm using super glue and I made the holes slightly bigger than they need to be, so it's fine. Also, I want the CNC machine to just do everything automatically to avoice human error.

# Threads

This adapter from SanwuLasers‚Ñ¢Ô∏è is the base of my design.\
It already comes with [male threads](./docs/sanwu_striker_adapter_male_view.jpg) and [female threads](./docs/sanwu_striker_adapter_female_view.jpg).

The part can be ordered via its [dedicated listing](./docs/sanwu_adapter_order_separately.png) on the website, or as part of the [flashlight converter listing](./docs/sanwu_adapter_in_flashlight_converter_listing.png).

The adapter is 17.55 mm in diameter, so I cut a 17.60mm hole in the cylinder of my custom design.

I [cut the adapter in half](./docs/sanwu_adapter_cut_in_half.jpg) using a [diamond blade circular saw](./docs/angle_grinder/angle_grinder_readme.pdf), sand it down, and super glue the male part into the large hole in one of my generic custom machined parts, and the female part of the adapter from Sanwu into another unit of my generic custom machined part.

This is my alternative to reverse-engineering the threads that Sanwu uses.

Just for general knowledge, Sanwu uses the following threading specs:

- Male:
  ```txt
  CNC machined
  Metric right-handed male threaded rod
  11.45mm diameter teeth (crest-to-crest). 0.05mm smaller diameter than the female tap.
  0.5mm pitch
  3mm length out of which only the tip 2mm are threaded and the base 1mm runoff is shaved down and not threaded.
  That's total of 4 threads.
  ```
- Female (laser head):
  ```txt
  CNC machined
  Metric right-handed female
  m11.5x0.5 tap (11.5mm diameter, 0.5mm pitch)
  6mm depth- total of 12 threads
  ```

I chose to use threads from an existing SanwuLasers‚Ñ¢Ô∏è adapter instead of printing my custom part [with designed threads](./docs/attempt_design_screw.png) for multiple reasons:
1. 11.5mm diameter is not standard.
2. Thread specification required English language specification, and can only exist in a step file for show (being pretty). This makes the whole process more expensive, and less automatic- it might make it hard for the CNC machine to know what to do!
3. I can always later design another custom stainless steel piece to fit into the generic 17.60mm hole with super glue, and I can decide to make it have threads! This incurs less risk by making the components modular.
4. Generic- single design works as either male or female screw side. Only having to print one step file multiple times is significantly cheaper because it only requires one preparation stage for Xometry.

# Recreate 3d model from code

You can decide to change parameters in [main.py](./main.py) then re-run the script to update the design files.

## Requirements
- Tested on Windows 11 Pro 23H2
- Ran with Python 3.10.6
- Specific versions chose: `pip install cadquery==2.4.0 numpy==1.23.5`

## Run
1. Delete the existing `.step` file and `.stl` file.
2. Run command `python magnet_holes_01_00_01.py` in a cmd Window in the same directory as the project folder.
3. Use the newly created `magnet_holes.stl` and `magnet_holes.step` for the male and female sides (upload to PCBWay CNC machining, or to Xometry).

# Release Notes

## magnet_holes_01_00_01
- 4.10mm diameter magnet holes for better fitting

## magnet_holes_01_00_00
[magnet_holes_01_00_00.py](./magnet_holes_01_00_00.py)\
[Final result](./docs/xometry_final_result.jpg)

- 4.04mm diameter magnet holes
- 5 units ordered with https://get.xometry.eu/payments/ec0325ff-71c7-4672-9496-26f8077902b1
```

# Instructions

Well, you saw what ChatGPT already managed to do, so I already have my hopes up for you to deliver and idiomatic and correct design!

Now let's get back to `rangers_guard_sleeve`.

The goal is to make it so the only way to pull off the flashlight head is directly up, so it cannot possibly accidentally fall off.

The Sanwu Striker has a build that is already sunk in, and that works great in stopping the flashlight adapter from accidentally breaking off / sliding off, so this design is specifically for the Sanwu Laser Rangers model which doesn't have that builtin fortunate compatibility.

Since we're designing the sleeve specifically for the `Rangers` we'll also make some cuts for the "stairs" that are manufactured into the head of most Laser Rangers models from Sanwu Lasers‚Ñ¢Ô∏è. These cuts won't be compatible with body types 3, 6, 9 (as seen in the listing at https://www.sanwulasers.com/product/laserrangers) which only have one stair on the head.

1. Start with a 30.20mm diameter, 23.2mm height cylinder as the base shape.

This is purposefully ~2mm wider than the 28mm diameter `magnet_holes`, to give us a 1mm wall thickness after some pockets, at the thinnest part of the design (which is the minimum for stainless steel).

2. Cut out a circular pocket 21.10mm in diameter from the center of the bottom of the base cylinder all the way to the top.

This is to fit the thinnest shape in this design- the top stair that is 21.00mm in diameter

3. Cut out a centered circular pocket at the top of the base cylinder, should be 28.10mm diameter pocket that has a 16.90mm depth.

Purpose: to tightly fit the bottom `magnet_holes` (male) piece as a structural hold to this entire design, with superglew to the base male piece that is screwed on to the laser head.\
16.9mm is the height of 2 `magnet_holes` + the gap between them.\
28.20mm is slightly wider than the 28mm wide `magnet_holes` cylinder diameter.

4. Cut out a slightly wider centered circular pocket at the top of the base cylinder (in addition to the one we already drilled out at the top), should be 28.20mm diameter pocket and 8.40mm depth.

Purpose: loosely fit the top `magnet_holes` (female) piece and stop it from accidentally disattaching while not blocking a user from yanking it upwards.\
8.40mm is slightly taller than 8.30mm which is the height of a single `magnet_holes` piece.\
28.20mm is purposefully wider than the 28mm wide `magnet_holes` cylinder diameter, and leaves walls that are exactly 1mm thick.

4. Cut out a wider centered circular pocket at the bottom of the base cylinder (in addition to the one we already drilled out at the bottom). It should be 25.10mm in diameter and 4.00mm in depth.

This is for the bottom stair which is 25.00mm in diameter.\
The total hight of the area of the stairs we want to encompass is 6.30mm in height, and I measured that for at least 2.30mm out of that total stair height the **small** stair is no more than 21.10mm. The pocket for the small stair was already dug out in an earlier step, therefore in this step we only dig in 6.30mm - 2.30mm == 4.00mm from the bottom.

Get to work!
